name: render

permissions:
  contents: write

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make out
      - name: upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: out/*.pdf
          overwrite: True

  export_svg:
    needs: build
    runs-on: ubuntu-latest
    steps:         
      - name: Download .pdf artifact
        uses: actions/download-artifact@v4
        with:
          name: PDFs
      - name: Export SVGs 
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install dvisvgm
          sudo apt-get -y install texlive-base
          mkdir svg
          for FILE in *.pdf; do sudo dvisvgm --pdf --output=svg/${FILE%%.*}.svg $FILE; done


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SVGs
          path: svg/*
          overwrite: True

  
