name: render

permissions:
  contents: write

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install zip
        run: |
          sudo apt-get update
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            apk add zip
            make zip
      - name: upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: out/*.pdf
          overwrite: True
